### ISSUE TITLE
how to use it under webpack

### ISSUE THREAD

**Issue by jiucheng-front** [pugjs/pug-loader#97]
Use webpack configuration development environment, how to use after installing pug-loader?

**Comment by drfisher** [comment]
@wjf444128852 Add this to your loaders list:

```javascript
loaders: [
  ...
  {
    test: /\.pug$/,
    loader: 'pug-loader'
  },
  ...
]
```

**Comment by jiucheng-front** [comment]
@drfisher TKS，This problem has been solved，
do you know how to include pug template to html ?

**Comment by BigLiao** [comment]
@wjf444128852 You can use in plugins:
`
plugins: [
      new HtmlWebpackPlugin({
          template: './src/index.pug',
       })
    ]
`

**Comment by jiucheng-front** [comment]
@BigLiao TKS  a lot

**Comment by ffpetrovic** [comment]
You have to alter your webpack config for every new page you want to make? Doesn't it defeat the whole purpose of templating?

**Comment by tomasdev** [comment]
@ffpetrovic no, it's a configuration thing
From https://stackoverflow.com/questions/44792582/how-to-output-html-files-from-pug-templates-with-webpack
```
{
    test: /\.pug$/,
    use: [
      "file-loader?name=[path][name].html",
      "extract-loader",
      "html-loader",
      "pug-html-loader"
    ]
  }
```

**Comment by jiucheng-front** [comment]
Tanks a lot, It has been resolved.

**Comment by mccxiv** [comment]
So yeah, `pug-html-loader` + `html-loader` solved my use case. Any way we can emulate that behavior in this package? I'd prefer it here since this one's official 😸

**Comment by ghost** [comment]
+1 Still having issues around webpack not being able to include pug. 

`You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

**Comment by ffpetrovic** [comment]
@betheldob https://github.com/ffpetrovic/ef-template/blob/master/webpack.config.js
